---
containers: []
virtualmachines:
  - name: "host1"
    image: "oracle-linux-9-6"
    bootloader: "efi"
    memory: "8G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
      - secondary
